version: '3'

networks:
  veramo-ssi:

services:
  veramoissuer:
    build:
      context: .

    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: typescript
    networks:
      - veramo-ssi
    expose:
      - '3002'
    ports:
      - '3002:3002'
    command: npm run start:docker