version: '3'

networks:
  earthid-ssi:

services:
  issuer.appnet.local.dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000
    networks:
      - earthid-ssi

  verifier.appnet.local.dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8001:8000
    networks:
      - earthid-ssi
